# Generated by Django 6.0.3 on 2026-08-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0009_property_has_pets_allowed_alter_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Gestionado')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Comisión pagada')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del huésped')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del huésped')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del huésped')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Comisión pagada')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado (USD)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status_updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización de estado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
