# Generated by Django 6.0.3 on 2026-08-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('internal', 'Reserva interna (web)'), ('external', 'Reserva externa (anfitrión)')], default='internal', max_length=20, verbose_name='Origen de la reserva'),
        ),
    ]
