# Generated by Django 6.0.3 on 2026-08-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_reservation'),
        ('leads', '0003_auto_20260818_0340'),
    ]

    operations = [
    ]
