# Generated by Django 6.0.3 on 2026-03-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(choices=[('varadero', 'Varadero'), ('santa_marta', 'Santa Marta'), ('guanabo', 'Guanabo'), ('boca_ciega', 'Boca Ciega'), ('penas_altas', 'Peñas Altas'), ('brisas_mar', 'Brisas del Mar'), ('habana_vieja', 'Habana Vieja'), ('centro_habana', 'Centro Habana'), ('vedado', 'Vedado'), ('nuevo_vedado', 'Nuevo Vedado'), ('playa', 'Playa'), ('fontanar', 'Fontanar'), ('calabazar', 'Calabazar'), ('vinales', 'Viñales'), ('trinidad', 'Trinidad')], max_length=50, verbose_name='Ubicación')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección exacta')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Habitaciones')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Huéspedes')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Baños')),
                ('rental_type', models.CharField(choices=[('entire', 'Toda la propiedad'), ('apartment', 'Solo un apartamento')], default='entire', max_length=20, verbose_name='Tipo de alquiler')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_tv', models.BooleanField(default=False, verbose_name='TV')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='Cocina')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parqueo')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscina')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Aire acondicionado')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por noche (USD)')),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por mes (USD)')),
                ('main_photo', models.ImageField(upload_to='properties/', verbose_name='Foto principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.category', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Pie de foto')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de propiedad',
                'verbose_name_plural': 'Imágenes de propiedades',
            },
        ),
    ]
