# Generated by Django 6.0.3 on 2026-03-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de contacto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Gestionado')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Comisión pagada')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto pagado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
