# Generated by Django 6.0.3 on 2026-04-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
        migrations.AddField(
            model_name='property',
            name='has_billiard',
            field=models.BooleanField(default=False, verbose_name='Billar'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_charcoal_oven',
            field=models.BooleanField(default=False, verbose_name='Horno al carbón'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_washing_machine',
            field=models.BooleanField(default=False, verbose_name='Lavadora'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_category',
            field=models.CharField(choices=[('night', 'Por noche'), ('month', 'Por mes'), ('daypass', 'Pasadía')], default='night', max_length=10, verbose_name='Categoría de precio'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_daypass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por pasadía (USD)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.category', verbose_name='Tipo de propiedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('vinales', 'Viñales, Pinar del Río'), ('playa', 'Playa, La Habana'), ('vedado', 'Vedado, La Habana'), ('nuevo_vedado', 'Nuevo Vedado, La Habana'), ('centro_habana', 'Centro Habana, La Habana'), ('habana_vieja', 'Habana Vieja, La Habana'), ('fontanar', 'Fontanar, La Habana'), ('calabazar', 'Calabazar, La Habana'), ('boca_ciega', 'Boca Ciega, La Habana'), ('guanabo', 'Guanabo, La Habana'), ('penas_altas', 'Peñas Altas, La Habana'), ('varadero', 'Varadero, Matanzas'), ('santa_marta', 'Santa Marta, Matanzas')], max_length=50, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(upload_to='', verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('entire', 'Toda la propiedad'), ('room', 'Por habitaciones')], default='entire', max_length=20, verbose_name='Tipo de alquiler'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')])),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('property', 'user')},
            },
        ),
    ]
