# Generated by Django 6.0.3 on 2026-04-25 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_main_photo_alter_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(upload_to='properties/main/', verbose_name='Foto principal'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_daypass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por pasadía (USD)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por mes (USD)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio por noche (USD)'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/gallery/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
