# Generated by Django 6.0.3 on 2026-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_has_billiard_property_has_charcoal_oven_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_category',
            field=models.CharField(choices=[('night', 'Por noche'), ('month', 'Por mes')], default='night', max_length=10, verbose_name='Categoría de precio'),
        ),
    ]
