# Generated by Django 6.0.3 on 2026-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_main_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('vinales', 'Viñales, Pinar del Río'), ('playa', 'Playa, La Habana'), ('vedado', 'Vedado, La Habana'), ('nuevo_vedado', 'Nuevo Vedado, La Habana'), ('centro_habana', 'Centro Habana, La Habana'), ('habana_vieja', 'Habana Vieja, La Habana'), ('fontanar', 'Fontanar, La Habana'), ('boca_ciega', 'Boca Ciega, La Habana'), ('guanabo', 'Guanabo, La Habana'), ('penas_altas', 'Peñas Altas, La Habana'), ('varadero', 'Varadero, Matanzas'), ('santa_marta', 'Santa Marta, Matanzas'), ('trinidad', 'Trinidad, Sancti Spíritus')], max_length=50, verbose_name='Ubicación'),
        ),
    ]
