# Generated by Django 6.0.3 on 2026-03-21 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.category', verbose_name='Tipo de propiedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rental_type',
            field=models.CharField(choices=[('entire', 'Toda la propiedad'), ('room', 'Por habitaciones')], default='entire', max_length=20, verbose_name='Tipo de alquiler'),
        ),
    ]
