# Generated by Django 6.0.3 on 2026-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_stable_electricity',
            field=models.BooleanField(default=False, verbose_name='Corriente eléctrica estable (respaldo)'),
        ),
    ]
