# Generated by Django 6.0.3 on 2026-03-27 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_category_alter_property_rental_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('vinales', 'Viñales, Pinar del Río'), ('playa', 'Playa, La Habana'), ('vedado', 'Vedado, La Habana'), ('nuevo_vedado', 'Nuevo Vedado, La Habana'), ('centro_habana', 'Centro Habana, La Habana'), ('habana_vieja', 'Habana Vieja, La Habana'), ('fontanar', 'Fontanar, La Habana'), ('calabazar', 'Calabazar, La Habana'), ('boca_ciega', 'Boca Ciega, La Habana'), ('guanabo', 'Guanabo, La Habana'), ('penas_altas', 'Peñas Altas, La Habana'), ('varadero', 'Varadero, Matanzas'), ('santa_marta', 'Santa Marta, Matanzas')], max_length=50, verbose_name='Ubicación'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='Calificación')),
                ('comment', models.TextField(max_length=500, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de valoración')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última edición')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='Propiedad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'user')},
            },
        ),
    ]
