# Generated by Django 6.0.3 on 2026-03-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_location_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_daypass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por pasadía (USD)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_category',
            field=models.CharField(choices=[('night', 'Por noche'), ('month', 'Por mes'), ('daypass', 'Pasadía')], default='night', max_length=10, verbose_name='Categoría de precio'),
        ),
    ]
