# Generated by Django 6.0.3 on 2026-05-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mostrar esta propiedad en la sección de destacados de la página principal', verbose_name='Destacado'),
        ),
    ]
