# Generated by Django 6.0.3 on 2026-08-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Se aceptan mascotas'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('vinales', 'Viñales, Pinar del Río'), ('playa', 'Playa, La Habana'), ('vedado', 'Vedado, La Habana'), ('nuevo_vedado', 'Nuevo Vedado, La Habana'), ('centro_habana', 'Centro Habana, La Habana'), ('habana_vieja', 'Habana Vieja, La Habana'), ('fontanar', 'Fontanar, La Habana'), ('boca_ciega', 'Boca Ciega, La Habana'), ('guanabo', 'Guanabo, La Habana'), ('varadero', 'Varadero, Matanzas'), ('santa_marta', 'Santa Marta, Matanzas')], max_length=50, verbose_name='Ubicación'),
        ),
    ]
